-- Create the waitlist table to store user emails
CREATE TABLE IF NOT EXISTS public.waitlist (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT waitlist_pkey PRIMARY KEY (id),
    CONSTRAINT waitlist_email_key UNIQUE (email)
);

-- Enable Row Level Security for the table
-- This is a security best practice, even if we only access it from the server.
ALTER TABLE IF EXISTS public.waitlist
    ENABLE ROW LEVEL SECURITY;
